### ISSUE TITLE
Timeouts should be handled silently

### ISSUE THREAD

**Issue by hufman** [ankeshanand/py-gfycat#1]
This library is wonderfully simple! However, if an upload takes longer than 30 seconds to convert, gfycat.com will time out, and the library returns this as an error to the main code.
It would be amazing if the library could catch this timeout error and keep checking the http://upload.gfycat.com/status/key url, returning when it is done. The `uploaded_file_info` looks ready to go, `upload_from_file` just has to do a loop if the upload is still in progress!
Thank you so much!

**Comment by ankeshanand** [comment]
@hufman Thanks for reporting the issue. I was not aware of the fact that gfycat.com times out over 30 seconds. Expect a fix soon!

**Comment by hufman** [comment]
If it helps, the exact exception I get looks like:

```
Traceback (most recent call last):
.....
  File ".../record.py", line 133, in upload_video
    upload = GfycatClient().upload_from_file(video)
  File ".../venv/local/lib/python2.7/site-packages/gfycat/client.py", line 57, in upload_from_file
    raise GfycatClientError(info['error'])
GfycatClientError: Connection timeout. Please check upload.gfycat.com/status/key for your finished conversion (details at gfycat.com/api)
```

I am using the pip installed `gfycat==0.1.3`

Thank you so much for this wonderful library!

**Comment by hufman** [comment]
Yeah, the exception is being raised when it checks for the info block. The json that is returned from `uploaded_file_info` looks like:
`{"error": "Connection timeout. Please check upload.gfycat.com/status/key for your finished conversion (details at gfycat.com/api)"}`

**Comment by hufman** [comment]
I've posted my workaround as #2
