### ISSUE TITLE
Cannot make instance from Class

### ISSUE THREAD

**Issue by qrx** [ankeshanand/py-gfycat#10]
```
Exception has occurred: TypeError
__init__() takes 1 positional argument but 3 were given
line 8, in main
    client = GfycatClient(my_id, my_secret)
```

Code:
```
from gfycat.client import GfycatClient


def main():
    my_id = 'some_id'
    my_secret = 'some_secret'
    client = GfycatClient(my_id, my_secret)

main()
```

**Comment by sporez** [comment]
The pip version of this project seems to be out of date, I had the same issue. If you download the source directly from GitHub and include it in your project that way, it works as expected.

**Comment by benslv** [comment]
I think you could probably also install it using pip like this:

`pip install gfycat==0.1.4`

**Comment by ankeshanand** [comment]
I have updated the pip package which should fix this! You can run

`pip install --upgrade gfycat` to update the package
