### ISSUE TITLE
Can't import client

### ISSUE THREAD

**Issue by mvinoba** [ankeshanand/py-gfycat#4]
Hello, I am trying to use the module and as soon as I import GfycatClient from gfycat.client I get the following error:

```
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    from gfycat.client import GfycatClient
  File "C:\Users\Vinicius\AppData\Local\Programs\Python\Python35-32\lib\site-packages\gfycat\client.py", line 4, in <module>
    from constants import (FETCH_URL_ENDPOINT, FETCH_URL_LAZY_ENDPOINT,
ImportError: No module named 'constants'
```

What am I doing wrong? Code is exactly that: 
`from gfycat.client import GfycatClient`

**Comment by ankeshanand** [comment]
Hi @mvinoba, there was an issue with imports for some users. I have updated the package on pypi to fix the error. Please reinstall the package, and it should work fine.
