### ISSUE TITLE
error 503 after every upload

### ISSUE THREAD

**Issue by bjuergens** [ankeshanand/py-gfycat#6]
Until 5 days ago this plugin worked perfectly, but then it just stopped working. For the last 5 days, every single upload resulted in a HTTP-Error 503 while checking the status. 

Did gfycat change something with their API or did they disable the upload from scripts?

Here are my upload-attempts over the last day: (after x unsuccessful attempts I drop the video and try again with the next one.)

[stabbot.log](https://github.com/ankeshanand/py-gfycat/files/1465715/stabbot.log)

**Comment by bjuergens** [comment]
idc anymore

**Comment by shrx** [comment]
Same issue here
