### ISSUE TITLE
Plans to support gfycat authentication?

### ISSUE THREAD

**Issue by pigi5** [ankeshanand/py-gfycat#7]
Do you have any plans to update this package to gfycat's new API, which supports many more functions and authentication?

**Comment by Frostlock** [comment]
Latest code looks to support API client id and secret but the pypi package pulls in older code without support for authentication.

**Comment by silverben10** [comment]
To get the most recent code will we need to clone this repo, then?

**Comment by Frostlock** [comment]
Yep, thats what I did :)

**Comment by ankeshanand** [comment]
I have updated the package on pip now as well!

**Comment by Frostlock** [comment]
All good now, thanks!
