### ISSUE TITLE
404 Unable to query for the GIF

### ISSUE THREAD

**Issue by corbindavenport** [ankeshanand/py-gfycat#8]
I can no longer query for any Gfycat URLs using the Python API. When I run this code:

```
client = GfycatClient()
      gfycat_info = client.query_gfy("InsecureIllegalDamselfly")
      # Download the Mp4 version
      gfycat_url = gfycat_info['gfyItem']['mp4Url']
```

I get this error:

```
gfycat.error.GfycatClientError: (404) Unable to query for the GIF
```

**Comment by AyeRlS** [comment]
Gfycat changed their api, here is a workaround
In gfycat/constants.py remplace the line 22 with this : 
QUERY_ENDPOINT = 'https://api.gfycat.com/v1/gfycats/'

**Comment by ghost** [comment]
@AyeRlS Did it happen again? I'm getting the same error for everything.
